### ISSUE TITLE
compile fairseq2n error

### ISSUE THREAD

**Issue by shanguanma** [facebookresearch/fairseq2#123]
**Describe the bug:**
I follow your install readme and step by step to install.
1. install pytorch
```conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia -c https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/linux-64/ -y```
2. install libsndfile
`conda install -c conda-forge libsndfile`
3. install comiler environment in conda
`conda install -c conda-forge compilers`
4.  compile fairseq2n
``` cmake -GNinja -DFAIRSEQ2N_INSTALL_STANDALONE=ON -DFAIRSEQ2N_USE_CUDA=ON -B build```
However , the error is as follows:

```
-- Found SndFile: /home/maduo/miniconda3/envs/fsq2/lib/libsndfile.so (found suitable version "1.0.31", minimum required is "1.0.25")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Checking for oneTBB under the Python environment...
-- Found TBB: /home/maduo/miniconda3/envs/fsq2/lib/libtbb.so (found suitable version "2021.8.0", minimum required is "2021.8")
-- Found Torch: /home/maduo/miniconda3/envs/fsq2/lib/python3.11/site-packages/torch/lib/libtorch.so (found suitable version "2.0.1", minimum required is "1.12")
-- Found Python3: /home/maduo/miniconda3/envs/fsq2/bin/python3.11 (found version "3.11.5") found components: Interpreter Development.Module
-- Module support is disabled.
-- Version: 9.1.0
-- Build type: RelWithDebInfo
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Required features: cxx_variadic_templates
CMake Deprecation Warning at third-party/kaldi-native-fbank/CMakeLists.txt:24 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- BUILD_SHARED_LIBS: FALSE
-- KALDI_NATIVE_FBANK_BUILD_TESTS: OFF
-- KALDI_NATIVE_FBANK_BUILD_PYTHON: OFF
-- KALDI_NATIVE_FBANK_ENABLE_CHECK: OFF
-- KALDI_NATIVE_FBANK_ENABLE_CHECK: OFF
-- CMAKE_CXX_FLAGS:
-- CMAKE_INSTALL_PREFIX: /usr/local
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Disable building Python
CMake Deprecation Warning at third-party/sentencepiece/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- VERSION: 0.1.97
-- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
CMake Deprecation Warning at third-party/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- pybind11 v2.10.0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found Python: /home/maduo/miniconda3/envs/fsq2/bin/python3.11 (found version "3.11.5") found components: Interpreter
CMake Error at /home/maduo/miniconda3/envs/fsq2/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:753 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda-11.7/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  1

  #$ _NVVM_BRANCH_=nvvm

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/local/cuda-11.7/bin

  #$ _THERE_=/usr/local/cuda-11.7/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_DIR_=targets/x86_64-linux

  #$ TOP=/usr/local/cuda-11.7/bin/..

  #$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-11.7/bin/../nvvm/libdevice

  #$
  LD_LIBRARY_PATH=/usr/local/cuda-11.7/bin/../lib:/usr/local/cuda-11.7/lib64::/workspace2/maduo/kaldi/src/base/:/workspace2/maduo/kaldi/src/fstext/:/workspace2/maduo/kaldi/tools/python:/workspace2/maduo/kaldi/src/bin:/workspace2/maduo/kaldi/src/chainbin:/workspace2/maduo/kaldi/src/featbin:/workspace2/maduo/kaldi/src/fgmmbin:/workspace2/maduo/kaldi/src/fstbin:/workspace2/maduo/kaldi/src/gmmbin:/workspace2/maduo/kaldi/src/ivectorbin:/workspace2/maduo/kaldi/src/kwsbin:/workspace2/maduo/kaldi/src/latbin:/workspace2/maduo/kaldi/src/lmbin:/workspace2/maduo/kaldi/src/nnet2bin:/workspace2/maduo/kaldi/src/nnet3bin:/workspace2/maduo/kaldi/src/nnetbin:/workspace2/maduo/kaldi/src/online2bin:/workspace2/maduo/kaldi/src/onlinebin:/workspace2/maduo/kaldi/src/rnnlmbin:/workspace2/maduo/kaldi/src/sgmm2bin:/workspace2/maduo/kaldi/src/sgmmbin:/workspace2/maduo/kaldi/src/tfrnnlmbin:/workspace2/maduo/kaldi/src/cudadecoderbin:/workspace2/maduo/kaldi/src/cudafeatbin:/workspace2/maduo/kaldi/tool/openfst/bin:/home/maduo/cmake-3.26.0/bin:/home/maduo/miniconda3/condabin:/usr/local/cuda-11.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


  #$
  PATH=/usr/local/cuda-11.7/bin/../nvvm/bin:/usr/local/cuda-11.7/bin:/home/maduo/miniconda3/envs/fsq2/bin:/workspace2/maduo/kaldi/tools/python:/workspace2/maduo/kaldi/src/bin:/workspace2/maduo/kaldi/src/chainbin:/workspace2/maduo/kaldi/src/featbin:/workspace2/maduo/kaldi/src/fgmmbin:/workspace2/maduo/kaldi/src/fstbin:/workspace2/maduo/kaldi/src/gmmbin:/workspace2/maduo/kaldi/src/ivectorbin:/workspace2/maduo/kaldi/src/kwsbin:/workspace2/maduo/kaldi/src/latbin:/workspace2/maduo/kaldi/src/lmbin:/workspace2/maduo/kaldi/src/nnet2bin:/workspace2/maduo/kaldi/src/nnet3bin:/workspace2/maduo/kaldi/src/nnetbin:/workspace2/maduo/kaldi/src/online2bin:/workspace2/maduo/kaldi/src/onlinebin:/workspace2/maduo/kaldi/src/rnnlmbin:/workspace2/maduo/kaldi/src/sgmm2bin:/workspace2/maduo/kaldi/src/sgmmbin:/workspace2/maduo/kaldi/src/tfrnnlmbin:/workspace2/maduo/kaldi/src/cudadecoderbin:/workspace2/maduo/kaldi/src/cudafeatbin:/workspace2/maduo/kaldi/tool/openfst/bin:/home/maduo/cmake-3.26.0/bin:/home/maduo/miniconda3/condabin:/usr/local/cuda-11.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


  #$ INCLUDES="-I/usr/local/cuda-11.7/bin/../targets/x86_64-linux/include"

  #$ LIBRARIES=
  "-L/usr/local/cuda-11.7/bin/../targets/x86_64-linux/lib/stubs"
  "-L/usr/local/cuda-11.7/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH__=520 -D__CUDA_ARCH_LIST__=520 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
  "-I/usr/local/cuda-11.7/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=7
  -D__CUDACC_VER_BUILD__=64 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=7 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include
  "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" -o
  "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++17 --gnu_version=110200 --display_error_number
  --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/workspace2/maduo/fairseq2/fairseq2n/build/CMakeFiles/3.27.7/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed -arch compute_52 -m64 --no-version-ident -ftz=0 -prec_div=1
  -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c"
  -tused --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_52 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_52.cubin"

  #$ fatbinary --create="tmp/CMakeCUDACompilerId.fatbin" -64
  --cicc-cmdline="-ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 "
  "--image3=kind=elf,sm=52,file=tmp/CMakeCUDACompilerId.sm_52.cubin"
  "--image3=kind=ptx,sm=52,file=tmp/CMakeCUDACompilerId.ptx"
  --embedded-fatbin="tmp/CMakeCUDACompilerId.fatbin.c"

  #$ gcc -D__CUDA_ARCH_LIST__=520 -E -x c++ -D__CUDACC__ -D__NVCC__
  "-I/usr/local/cuda-11.7/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=7
  -D__CUDACC_VER_BUILD__=64 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=7 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include
  "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" -o
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  #$ cudafe++ --c++17 --gnu_version=110200 --display_error_number
  --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/workspace2/maduo/fairseq2/fairseq2n/build/CMakeFiles/3.27.7/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed --m64 --parse_templates --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name
  "CMakeCUDACompilerId.cudafe1.stub.c" --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" "tmp/CMakeCUDACompilerId.cpp4.ii"

  #$ gcc -D__CUDA_ARCH__=520 -D__CUDA_ARCH_LIST__=520 -c -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS
  "-I/usr/local/cuda-11.7/bin/../targets/x86_64-linux/include" -m64
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" -o "tmp/CMakeCUDACompilerId.o"

  #$ nvlink -m64 --arch=sm_52 --register-link-binaries="tmp/a_dlink.reg.c"
  "-L/usr/local/cuda-11.7/bin/../targets/x86_64-linux/lib/stubs"
  "-L/usr/local/cuda-11.7/bin/../targets/x86_64-linux/lib" -cpu-arch=X86_64
  "tmp/CMakeCUDACompilerId.o" -lcudadevrt -o "tmp/a_dlink.sm_52.cubin"
  --host-ccbin "gcc"

  #$ fatbinary --create="tmp/a_dlink.fatbin" -64 --cicc-cmdline="-ftz=0
  -prec_div=1 -prec_sqrt=1 -fmad=1 " -link
  "--image3=kind=elf,sm=52,file=tmp/a_dlink.sm_52.cubin"
  --embedded-fatbin="tmp/a_dlink.fatbin.c"

  #$ gcc -D__CUDA_ARCH_LIST__=520 -c -x c++
  -DFATBINFILE="\"tmp/a_dlink.fatbin.c\""
  -DREGISTERLINKBINARYFILE="\"tmp/a_dlink.reg.c\"" -I.
  -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION=
  -D__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__
  "-I/usr/local/cuda-11.7/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=7
  -D__CUDACC_VER_BUILD__=64 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=7 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -m64
  "/usr/local/cuda-11.7/bin/crt/link.stub" -o "tmp/a_dlink.o"

  #$ g++ -D__CUDA_ARCH_LIST__=520 -m64 -Wl,--start-group "tmp/a_dlink.o"
  "tmp/CMakeCUDACompilerId.o"
  "-L/usr/local/cuda-11.7/bin/../targets/x86_64-linux/lib/stubs"
  "-L/usr/local/cuda-11.7/bin/../targets/x86_64-linux/lib" -lcudadevrt
  -lcudart_static -lrt -lpthread -ldl -Wl,--end-group -o "a.out"


  /home/maduo/miniconda3/envs/fsq2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld:
  /home/maduo/miniconda3/envs/fsq2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/lib/../lib64/libstdc++.so:
  undefined reference to `memcpy@GLIBC_2.14'


  /home/maduo/miniconda3/envs/fsq2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld:
  /home/maduo/miniconda3/envs/fsq2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/lib/../lib64/libstdc++.so:
  undefined reference to `aligned_alloc@GLIBC_2.16'


  /home/maduo/miniconda3/envs/fsq2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld:
  /home/maduo/miniconda3/envs/fsq2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/lib/../lib64/libstdc++.so:
  undefined reference to `clock_gettime@GLIBC_2.17'

  collect2: error: ld returned 1 exit status

  # --error 0x1 --





Call Stack (most recent call first):
  /home/maduo/miniconda3/envs/fsq2/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /home/maduo/miniconda3/envs/fsq2/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /home/maduo/miniconda3/envs/fsq2/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:220 (enable_language)


-- Configuring incomplete, errors occurred!
```
**Environment:**
pytorch 2.0.1, cuda 11.7
python3.11,
operating system: 20.04.2 LTS (GNU/Linux 5.8.0-43-generic x86_64)

**Comment by cbalioglu** [comment]
Hey @shanguanma, we do not support building fairseq2n + CUDA in a Conda environment. It should work as long as you make sure that you use the exact toolchain for both host and device code, but it is tricky in Conda environments. Having said that yesterday I made an improvement that allows you to use the latest fairseq2n nightlies with `pip install -e.`. I updated the instructions [here](https://github.com/facebookresearch/fairseq2/blob/main/CONTRIBUTING.md#setting-up-development-environment). Please try it out and let me know how it goes.

**Comment by shanguanma** [comment]
> Hey @shanguanma, we do not support building fairseq2n + CUDA in a Conda environment. It should work as long as you make sure that you use the exact toolchain for both host and device code, but it is tricky in Conda environments. Having said that yesterday I made an improvement that allows you to use the latest fairseq2n nightlies with `pip install -e.`. I updated the instructions [here](https://github.com/facebookresearch/fairseq2/blob/main/CONTRIBUTING.md#setting-up-development-environment). Please try it out and let me know how it goes.

Thanks for your reply, your suggestion is working now, I posted the deatil steps, it maybe useful to others.
```
git clone https://github.com/facebookresearch/fairseq2.git

conda create -n fairseq2 python=3.11 -y

conda activate fairseq2

conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia -c https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/linux-64/ -y

cd fairseq2
## install fairseq2n 
pip install fairseq2n  --pre --upgrade --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/nightly/pt2.0.1/cu117
## install fairseq2
pip install -e .

```

**Comment by shanguanma** [comment]
> > Hey @shanguanma, we do not support building fairseq2n + CUDA in a Conda environment. It should work as long as you make sure that you use the exact toolchain for both host and device code, but it is tricky in Conda environments. Having said that yesterday I made an improvement that allows you to use the latest fairseq2n nightlies with `pip install -e.`. I updated the instructions [here](https://github.com/facebookresearch/fairseq2/blob/main/CONTRIBUTING.md#setting-up-development-environment). Please try it out and let me know how it goes.
> 
> Thanks for your reply, your suggestion is working now, I posted the deatil steps, it maybe useful to others.
> 
> ```
> git clone https://github.com/facebookresearch/fairseq2.git
> 
> conda create -n fairseq2 python=3.11 -y
> 
> conda activate fairseq2
> 
> conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia -c https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/linux-64/ -y
> 
> cd fairseq2
> ## install fairseq2n 
> pip install fairseq2n  --pre --upgrade --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/nightly/pt2.0.1/cu117
> ## install fairseq2
> pip install -e .
> ```



> Hey @shanguanma, we do not support building fairseq2n + CUDA in a Conda environment. It should work as long as you make sure that you use the exact toolchain for both host and device code, but it is tricky in Conda environments. Having said that yesterday I made an improvement that allows you to use the latest fairseq2n nightlies with `pip install -e.`. I updated the instructions [here](https://github.com/facebookresearch/fairseq2/blob/main/CONTRIBUTING.md#setting-up-development-environment). Please try it out and let me know how it goes.

however, I occurs other problem, I can't import fairseq2.nn libriary. the error is as follows:
```
export PYTHONPATH=/workspace2/maduo/fairseq2/src/fairseq2:$PYTHONPATH
(fairseq2) maduo@lthpc-SYS-4029GP-TRT-BA001:/workspace2/maduo/fairseq2$ python
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fairseq2.data.text.text_tokenizer import TextTokenDecoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fairseq2.data'
>>> from fairseq2.data.typing import PathLike
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fairseq2.data'
>>> from fairseq2.nn.transformer import TransformerEncoder, TransformerNormOrder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fairseq2.nn'
```
