### ISSUE TITLE
Use fairseq2 without a gpu?

### ISSUE THREAD

**Issue by ChenyuZhang16** [facebookresearch/fairseq2#36]
Hi folks! Is there a way to run fairseq2 on a machine without GPU? I'm getting the following error trying to use it on my cpu only machine:
```
>>> from fairseq2.data import Collater
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czhang/Documents/work/venv/lib/python3.8/site-packages/fairseq2/data/__init__.py", line 7, in <module>
    from fairseq2.data.cstring import CString as CString
  File "/home/czhang/Documents/work/venv/lib/python3.8/site-packages/fairseq2/data/cstring.py", line 58, in <module>
    from fairseq2n.bindings.data.string import CString as CString
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

**Comment by ChenyuZhang16** [comment]
Just followed the [build fairseq2 from source](https://github.com/facebookresearch/fairseq2/blob/main/INSTALL_FROM_SOURCE.md) and build a cpu-only version. Seems to have solved my problem.

So will close the issue for now.
