### ISSUE TITLE
Dosen't recongnize libsndfile even though it's installed

### ISSUE THREAD

**Issue by guranu** [facebookresearch/fairseq2#51]
Hello, so i wanted to try seamlessm4t i followed the instructions but when i type `m4t_predict` i get an error saying that libsndfile isn't installed but it is installed i don't have conda installed: 
```
~ $ apt install libsndfile
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libsndfile is already the newest version (1.2.2).
The following packages were automatically installed and are no longer required:
  adwaita-icon-theme arj aspell at-spi2-core atk
  bsdtar cpio dbus dconf desktop-file-utils enchant
  exo file-roller fontconfig-utils garcon gcr
  gdk-pixbuf glib-bin glib-networking graphene
  gsettings-desktop-schemas gst-plugins-base gstreamer
  gtk-update-icon-cache gtk3 gvfs harfbuzz-icu
  hicolor-icon-theme hunspell hunspell-en-us imlib2
  iso-codes json-glib libcaca libde265 libdrm libepoxy
  libexif libfontenc libglvnd libhandy libheif
  libhyphen libicu libid3tag libimagequant libjxl
  libltdl libnotify libpsl libraqm librsvg libsoup3
  libtasn1 libvte libwayland
  libwebrtc-audio-processing libwnck libxcomposite
  libxcursor libxdamage libxfce4ui libxfce4util
  libxfixes libxfont2 libxft libxinerama libxkbfile
  libxklavier libxshmfence libxv libxxf86vm
  lxde-icon-theme lz4 lzip lzop mesa openal-soft
  opengl p11-kit p7zip pango python-pillow
  shared-mime-info speexdsp startup-notification
  thunar thunar-archive-plugin tumbler unrar
  vulkan-loader vulkan-loader-android woff2 xcb-util
  xfce4-notifyd xfce4-panel xfce4-session
  xfce4-settings xfce4-terminal xfconf xfdesktop xfwm4
  xkeyboard-config xorg-font-util xorg-fonts-75dpi
  xorg-fonts-alias xorg-fonts-encodings xorg-iceauth
  xorg-mkfontscale xorg-xkbcomp xorg-xrdb zip
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
~ $ m4t_predict
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/m4t_predict", line 5, in <module>
    from m4t_scripts.predict.predict import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/m4t_scripts/predict/predict.py", line 10, in <module>
    from seamless_communication.models.inference import Translator
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/seamless_communication/models/inference/__init__.py", line 6, in <module>
    from seamless_communication.models.inference.translator import Translator as Translator
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/seamless_communication/models/inference/translator.py", line 11, in <module>
    from fairseq2.assets.card import AssetCard
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fairseq2/__init__.py", line 9, in <module>
    import fairseq2n
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fairseq2n/__init__.py", line 110, in <module>
    _load_shared_libraries()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fairseq2n/__init__.py", line 33, in _load_shared_libraries
    _load_sndfile()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fairseq2n/__init__.py", line 62, in _load_sndfile
    raise OSError(
OSError: libsndfile is not found! Use your system package manager to install it (e.g. `apt install libsndfile1`)
```

**Comment by romanovj** [comment]
create softlink

ln -s /data/data/com.termux/files/usr/lib/libsndfile.so /data/data/com.termux/files/usr/lib/libsndfile.so.1

**Comment by guranu** [comment]
> create softlink
> 
> `ln -s /data/data/com.termux/files/usr/lib/libsndfile.so /data/data/com.termux/files/usr/lib/libsndfile.so.1`
> 
> ubuntu package: libsndfile.so.1 -> libsndfile.so.1.0.35 libsndfile.so.1.0.35
> 
> termux package: libsndfile.so

Thanks it worked.
